const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let contacts=[],configured=false,poll;
const toast=t=>{const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3500)};
function page(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));$('#crumb').textContent=id.toUpperCase();$('#page-title').textContent={overview:'Campaign overview',contacts:'Audience manager',campaign:'New campaign',activity:'Delivery activity'}[id];$('#sidebar').classList.remove('open');if(id==='activity')refreshCampaign()}
$$('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');
function csvLine(line){let out=[],v='',q=false;for(let i=0;i<line.length;i++){let c=line[i];if(c==='"'&&q&&line[i+1]==='"'){v+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){out.push(v.trim());v=''}else v+=c}out.push(v.trim());return out}
function parseCsv(text){let lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)throw Error('CSV contains no contacts.');if(lines.length>1001)throw Error('Maximum 1,000 contacts.');let h=csvLine(lines.shift()).map(x=>x.toLowerCase()),pi=h.indexOf('phone'),ci=h.indexOf('country_code');if(pi<0||ci<0)throw Error('CSV needs phone and country_code columns.');let map=new Map;lines.forEach((l,i)=>{let r=csvLine(l),p=(r[pi]||'').replace(/\D/g,''),cc=(r[ci]||'').replace(/\D/g,''),full=p.length===10?cc+p:p;if(!cc||full.length<11||full.length>15)throw Error(`Invalid phone or country code on row ${i+2}.`);map.set(full,{phone:p,countryCode:cc})});return [...map.values()]}
async function loadContacts(){let r=await fetch('/api/contacts'),d=await r.json();contacts=d.contacts||[];renderContacts();updateCounts()}
function updateCounts(){$('#nav-count').textContent=contacts.length;$('#stat-contacts').textContent=contacts.length;$('#contact-total').textContent=`${contacts.length} contacts`;$('#audience').textContent=`${contacts.length} recipients ready`;$('#review').disabled=!configured||!contacts.length;$('#test').disabled=!configured||!contacts.length;if($('#clear-contacts'))$('#clear-contacts').disabled=!contacts.length}
function renderContacts(filter=''){let body=$('#contact-rows'),list=contacts.filter(c=>c.fullPhone.includes(filter.replace(/\D/g,'')));body.innerHTML=list.map(c=>`<tr><td><strong>+${c.fullPhone}</strong></td><td>+${c.countryCode}</td><td><span class="chip">Opted in</span></td></tr>`).join('');$('#contact-empty').classList.toggle('hide',contacts.length>0)}
$('#search').oninput=e=>renderContacts(e.target.value);
async function importFile(file){try{let parsed=parseCsv(await file.text()),r=await fetch('/api/import-contacts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contacts:parsed})}),d=await r.json();if(!r.ok)throw Error(d.error);$('#notice').textContent=`✓ ${d.count} unique contacts imported successfully.`;$('#notice').classList.remove('hide');await loadContacts();toast('Contact list updated')}catch(e){toast(e.message)}}
$('#file').onchange=e=>e.target.files[0]&&importFile(e.target.files[0]);let drop=$('#drop');drop.onclick=()=>$('#file').click();['dragenter','dragover'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.ondrop=e=>e.dataTransfer.files[0]&&importFile(e.dataTransfer.files[0]);
$('#message').oninput=e=>{$('#chars').textContent=`${[...e.target.value].length} / 4096`;$('#preview').childNodes[0].nodeValue=(e.target.value||'Your message preview')+' '};
async function status(){try{let r=await fetch('/api/status'),d=await r.json();configured=d.configured;$('#api-dot').classList.toggle('live',configured);$('#api-title').textContent=configured?'MudBot configured':'Setup required';$('#api-detail').textContent=configured?d.baseUrl:(d.missing||[]).join(', ');updateCounts()}catch{$('#api-title').textContent='Server offline'}}
$('#review').onclick=()=>{if(!$('#consent').checked)return toast('Confirm recipient consent first.');if(!$('#message').value.trim())return toast('Write a message first.');$('#review-count').textContent=contacts.length;$('#review-text').textContent=$('#message').value.trim();$('#modal').classList.remove('hide')};
const close=()=>$('#modal').classList.add('hide');$('#modal-close').onclick=close;$('#cancel').onclick=close;
$('#launch').onclick=async()=>{let body={name:$('#campaign-name').value.trim()||'Untitled campaign',message:$('#message').value.trim(),consent:true};$('#launch').disabled=true;try{let r=await fetch('/api/campaigns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error);close();page('activity');toast('Campaign launched');refreshCampaign()}catch(e){toast(e.message)}finally{$('#launch').disabled=false}};
$('#test').onclick=async()=>{if(!$('#consent').checked)return toast('Confirm recipient consent first.');if(!confirm(`Send one test to +${contacts[0].fullPhone}?`))return;$('#test').disabled=true;try{let r=await fetch('/api/send-text',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:contacts[0].fullPhone,message:$('#message').value.trim()})}),d=await r.json();if(!r.ok)throw Error(d.error);toast('Test message sent')}catch(e){toast(`Test failed: ${e.message}`)}finally{$('#test').disabled=false}};
$('#stop').onclick=async()=>{if(!confirm('Stop after the current message finishes?'))return;await fetch('/api/campaigns/stop',{method:'POST'});refreshCampaign()};const clearActivity=document.createElement('button');clearActivity.className='btn secondary';clearActivity.textContent='Clear activity';$('#activity .heading').append(clearActivity);clearActivity.onclick=async()=>{if(!confirm('Clear all local activity history? This cannot be undone.'))return;let r=await fetch('/api/activity',{method:'DELETE'}),d=await r.json();if(!r.ok)return toast(d.error);toast('Activity cleared');refreshCampaign()};
function activityHtml(items){return items.length?items.map(x=>`<div class="activity-item"><i>${x.type==='sent'?'✓':x.type==='failed'?'!':'↗'}</i><span><strong>${x.text}</strong><small>${new Date(x.at).toLocaleString()}</small></span></div>`).join(''):'Nothing to show yet.'}
async function refreshCampaign(){try{let r=await fetch('/api/campaigns/current'),d=await r.json(),c=d.campaign||{status:'idle',total:0,processed:0,sent:0,failed:0,name:'No campaign running'},pct=c.total?Math.round(c.processed/c.total*100):0;$('#run-name').textContent=c.name;$('#run-percent').textContent=pct+'%';$('#run-progress').style.width=pct+'%';$('#run-processed').textContent=c.processed;$('#run-sent').textContent=c.sent;$('#run-failed').textContent=c.failed;$('#run-dot').classList.toggle('live',c.status==='running'||c.status==='stopping');$('#stop').disabled=c.status!=='running';$('#stat-status').textContent=c.status[0].toUpperCase()+c.status.slice(1);$('#stat-detail').textContent=c.total?`${c.processed} of ${c.total} processed`:'No campaign running';$('#stat-sent').textContent=d.sessionSent||0;$('#activity-list').innerHTML=activityHtml(d.activity||[]);$('#activity-list').classList.toggle('empty',!(d.activity||[]).length);$('#activity-preview').innerHTML=activityHtml((d.activity||[]).slice(0,3));$('#activity-preview').classList.toggle('empty',!(d.activity||[]).length)}catch{}clearTimeout(poll);poll=setTimeout(refreshCampaign,2000)}
const clearButton=document.createElement('button');clearButton.id='clear-contacts';clearButton.className='btn danger';clearButton.textContent='Clear all contacts';const contactHeading=$('#contacts .heading');contactHeading.append(clearButton);clearButton.onclick=async()=>{if(!contacts.length)return;if(!confirm(`Permanently remove all ${contacts.length} contacts from contacts.csv? This cannot be undone.`))return;clearButton.disabled=true;try{let r=await fetch('/api/contacts',{method:'DELETE'}),d=await r.json();if(!r.ok)throw Error(d.error);await loadContacts();$('#notice').textContent=`All contacts were removed. contacts.csv is now empty.`;$('#notice').classList.remove('hide');toast('Contact list cleared')}catch(e){toast(e.message);updateCounts()}};$('#drop p').textContent='phone, country_code · maximum 1,000 contacts';$('#search').placeholder='Search phone number…';$('#contacts thead tr').innerHTML='<th>Phone number</th><th>Country code</th><th>Permission</th>';
status();loadContacts();refreshCampaign();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
